apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: parser
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: parser
            image: busybox
          restartPolicy: OnFailure